#!/bin/bash
# Setup automated daily backups using cron
# Run this script once to configure automated backups

set -e

echo "=========================================="
echo "SL Academy - Backup Automation Setup"
echo "=========================================="

# Get script directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Configuration
BACKUP_SCRIPT="$SCRIPT_DIR/backup_database.py"
BACKUP_TIME="${BACKUP_TIME:-02:00}"  # Default: 2 AM
BACKUP_DIR="${BACKUP_DIR:-$PROJECT_ROOT/backups}"
LOG_DIR="${LOG_DIR:-$PROJECT_ROOT/logs}"

# Create directories
mkdir -p "$BACKUP_DIR"
mkdir -p "$LOG_DIR"

echo "Configuration:"
echo "  Backup script: $BACKUP_SCRIPT"
echo "  Backup time: $BACKUP_TIME daily"
echo "  Backup directory: $BACKUP_DIR"
echo "  Log directory: $LOG_DIR"
echo ""

# Check if Python script exists
if [ ! -f "$BACKUP_SCRIPT" ]; then
    echo "Error: Backup script not found: $BACKUP_SCRIPT"
    exit 1
fi

# Make script executable
chmod +x "$BACKUP_SCRIPT"

# Create wrapper script for cron
CRON_WRAPPER="$SCRIPT_DIR/backup_cron_wrapper.sh"
cat > "$CRON_WRAPPER" << EOF
#!/bin/bash
# Cron wrapper for backup script
# Generated by setup_backup_cron.sh

# Load environment variables
if [ -f "$PROJECT_ROOT/.env" ]; then
    export \$(cat "$PROJECT_ROOT/.env" | grep -v '^#' | xargs)
fi

# Set backup directory
export BACKUP_DIR="$BACKUP_DIR"

# Run backup script
cd "$PROJECT_ROOT"
python3 "$BACKUP_SCRIPT" >> "$LOG_DIR/backup.log" 2>&1

# Log completion
echo "\$(date): Backup completed" >> "$LOG_DIR/backup_cron.log"
EOF

chmod +x "$CRON_WRAPPER"

# Parse backup time (HH:MM)
HOUR=$(echo "$BACKUP_TIME" | cut -d: -f1)
MINUTE=$(echo "$BACKUP_TIME" | cut -d: -f2)

# Create cron entry
CRON_ENTRY="$MINUTE $HOUR * * * $CRON_WRAPPER"

echo "Cron entry to be added:"
echo "  $CRON_ENTRY"
echo ""

# Check if cron entry already exists
if crontab -l 2>/dev/null | grep -q "$CRON_WRAPPER"; then
    echo "Cron entry already exists. Updating..."
    crontab -l 2>/dev/null | grep -v "$CRON_WRAPPER" | crontab -
fi

# Add cron entry
(crontab -l 2>/dev/null; echo "$CRON_ENTRY") | crontab -

echo "✓ Cron job configured successfully"
echo ""
echo "Backup will run daily at $BACKUP_TIME"
echo "Logs will be written to: $LOG_DIR/backup.log"
echo ""
echo "To view current cron jobs:"
echo "  crontab -l"
echo ""
echo "To remove backup cron job:"
echo "  crontab -l | grep -v '$CRON_WRAPPER' | crontab -"
echo ""
echo "To test backup manually:"
echo "  $CRON_WRAPPER"
echo ""
echo "=========================================="
echo "Setup completed successfully!"
echo "=========================================="
