-- Fase 4: Vigilante de Diretrizes (Scrapling Watcher)
-- Tabela de alertas clínicos gerados pelo monitoramento automático de diretrizes

-- ============================================================================
-- CLINICAL ALERTS
-- Stores alerts generated by the Scrapling Watcher when it detects new or
-- updated clinical guidelines on external sources (PubMed, Ministério da Saúde, etc.)
-- The watcher runs as a background task; managers review and dismiss alerts.
-- ============================================================================

CREATE TYPE alert_severity AS ENUM ('info', 'warning', 'critical');

CREATE TABLE clinical_alerts (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    hospital_id     UUID NOT NULL REFERENCES hospitals(id) ON DELETE CASCADE,
    track_id        UUID REFERENCES tracks(id) ON DELETE SET NULL,
    source          TEXT NOT NULL,           -- e.g. 'pubmed', 'ministerio_saude'
    title           TEXT NOT NULL,
    url             TEXT,
    summary         TEXT,
    severity        alert_severity NOT NULL DEFAULT 'info',
    is_read         BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_clinical_alerts_hospital ON clinical_alerts(hospital_id, is_read);
CREATE INDEX idx_clinical_alerts_track    ON clinical_alerts(track_id);
CREATE INDEX idx_clinical_alerts_created  ON clinical_alerts(created_at DESC);

-- ── RLS ───────────────────────────────────────────────────────────────────────

ALTER TABLE clinical_alerts ENABLE ROW LEVEL SECURITY;

-- All staff (doctor + manager) can read alerts for their hospital
CREATE POLICY "Hospital staff can read clinical alerts"
  ON clinical_alerts FOR SELECT
  USING (hospital_id = public.user_hospital_id());

-- Only managers can mark alerts as read / update
CREATE POLICY "Managers can update clinical alerts"
  ON clinical_alerts FOR UPDATE
  USING (
    hospital_id = public.user_hospital_id()
    AND public.is_manager()
  );

-- Only managers can delete alerts
CREATE POLICY "Managers can delete clinical alerts"
  ON clinical_alerts FOR DELETE
  USING (
    hospital_id = public.user_hospital_id()
    AND public.is_manager()
  );

-- INSERT is performed by the backend via service role key (bypasses RLS)

-- ── Comments ──────────────────────────────────────────────────────────────────

COMMENT ON TABLE clinical_alerts IS
  'Fase 4: alerts generated by the Scrapling Watcher when new clinical
   guidelines are detected on external sources. Managed by hospital managers.';

COMMENT ON COLUMN clinical_alerts.source    IS 'Origin site slug: pubmed | ministerio_saude | uptodate | etc.';
COMMENT ON COLUMN clinical_alerts.track_id  IS 'Track the alert is related to (optional — may be NULL for global alerts).';
COMMENT ON COLUMN clinical_alerts.severity  IS 'info = new guideline; warning = major update; critical = safety recall.';
COMMENT ON COLUMN clinical_alerts.is_read   IS 'Manager acknowledged / dismissed this alert.';
