-- ============================================================================
-- Phase 6: Occupational Health — Burnout Alerts & Micro-Learning
-- ============================================================================
-- 1. Burnout alerts — generated by the burnout analyzer, acknowledged by managers
CREATE TABLE IF NOT EXISTS burnout_alerts (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    hospital_id UUID NOT NULL REFERENCES hospitals(id) ON DELETE CASCADE,
    doctor_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    risk_level TEXT NOT NULL CHECK (
        risk_level IN ('low', 'medium', 'high', 'critical')
    ),
    triggers TEXT [] NOT NULL DEFAULT '{}',
    is_acknowledged BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT now()
);
-- 2. Micro-learning tasks — recertification assignments for expired POPs
CREATE TABLE IF NOT EXISTS micro_learning_tasks (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    hospital_id UUID NOT NULL REFERENCES hospitals(id) ON DELETE CASCADE,
    doctor_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    track_id UUID NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'passed', 'failed')),
    due_date DATE,
    created_at TIMESTAMPTZ DEFAULT now()
);
-- ── RLS ──────────────────────────────────────────────────────────────────────
ALTER TABLE burnout_alerts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "burnout_alerts_select" ON burnout_alerts FOR
SELECT USING (
        hospital_id IN (
            SELECT hospital_id
            FROM profiles
            WHERE id = auth.uid()
        )
    );
CREATE POLICY "burnout_alerts_update" ON burnout_alerts FOR
UPDATE USING (
        hospital_id IN (
            SELECT hospital_id
            FROM profiles
            WHERE id = auth.uid()
                AND role = 'manager'
        )
    );
ALTER TABLE micro_learning_tasks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "micro_learning_tasks_select" ON micro_learning_tasks FOR
SELECT USING (
        hospital_id IN (
            SELECT hospital_id
            FROM profiles
            WHERE id = auth.uid()
        )
    );
CREATE POLICY "micro_learning_tasks_insert" ON micro_learning_tasks FOR
INSERT WITH CHECK (
        hospital_id IN (
            SELECT hospital_id
            FROM profiles
            WHERE id = auth.uid()
                AND role = 'manager'
        )
    );
CREATE POLICY "micro_learning_tasks_update" ON micro_learning_tasks FOR
UPDATE USING (
        hospital_id IN (
            SELECT hospital_id
            FROM profiles
            WHERE id = auth.uid()
        )
    );
-- ── Indexes ──────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_burnout_alerts_hospital_active ON burnout_alerts(hospital_id, created_at DESC)
WHERE is_acknowledged = false;
CREATE INDEX IF NOT EXISTS idx_burnout_alerts_doctor ON burnout_alerts(doctor_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_micro_learning_hospital_pending ON micro_learning_tasks(hospital_id, status)
WHERE status = 'pending';
CREATE INDEX IF NOT EXISTS idx_micro_learning_doctor ON micro_learning_tasks(doctor_id, status);